# Generated by Django 3.2.3 on 2021-07-14 17:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='incentives',
            field=models.CharField(default=10000, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='other',
            field=models.CharField(default=5000, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
