# Generated by Django 3.2.5 on 2021-07-09 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('reason', models.CharField(max_length=1000)),
                ('payment_terms', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=20)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice')),
            ],
        ),
    ]
